### ISSUE TITLE
Improve coverage

### ISSUE THREAD

**Issue by a17** [stabilitydao/stability-contracts#120]
Let's improve the overall percentage of project test coverage.

**Comment by hcrypto7** [comment]
improved coverage in quickswap strategy.
as total Lines coverage 98.07%(0.03% up) Statements coverage 98.33%(0.02% up).

**Comment by hcrypto7** [comment]
![image](https://github.com/stabilitydao/stability-contracts/assets/153700650/55b0fde7-6a72-4572-9b32-e170da9de0f5)
I  have passed forge test on local env, but when send PR, I failed on test.
