### ISSUE TITLE
📜[DEV] Steer QuickSwap Merkl Farm

### ISSUE THREAD

**Issue by a17** [stabilitydao/stability-contracts#85]
# SQMF

## Status: DEV

*Being developed.*

## Description

Earn MERKL rewards by Steer vault.

## Base contracts

* LPStrategyBase
* FarmingStrategyBase

## Adapters

* AmmAdapterIdLib.ALGEBRA

**Comment by a17** [comment]
* [SteerPeriphery.sol](https://polygonscan.com/address/0x5f49b0e07e4d147085f1ad7725ecf2311263122c#code)
* Steer WMATIC/USDC vault `0x280bE4533891E887F55847A773B93d043984Fbd5`  [UI](https://app.steer.finance/vault/0x280be4533891e887f55847a773b93d043984fbd5)
* Steer WBTC/WETH vault `0x12a7b5510f8f5E13F75aFF4d00b2F88CC99d22DB` [UI](https://app.steer.finance/vault/0x12a7b5510f8f5e13f75aff4d00b2f88cc99d22db)

**Comment by OnlyForward0613** [comment]
Hello, should I use quickswap pool address or create a pool for steer strategy?
As far as i check the route2() function, there is not defiedge route part in PolygonLib.sol.
